---
dokuwiki_version: "stable"
dokuwiki_url: "https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz"
dokuwiki_dir: "/var/www/dokuwiki/dokuwiki-2025-05-14b"
dokuwiki_owner: "apache"
dokuwiki_group: "apache"
dokuwiki_title: "Magnum Opus Wiki"
dokuwiki_admin_user: "admin"
