dokuwiki_dir: /var/www/dokuwiki/dokuwiki-2025-05-14b
dokuwiki_group: apache
dokuwiki_owner: apache
dokuwiki_title: Magnum Opus Wiki
dokuwiki_url: "https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz"

